res/text/bms_page_en.txt, src/nmania/PlayOptions.java, src/nmania/Player.java, src/nmania/PlayerLoader.java, src/nmania/ui/BeatmapSetPage.java
Close #13
- HR/EZ match osu!stable.
- NF matches osu!stable.
- SD works by setting `-1001` as health impact for `miss`.
- No icons for now. I will try to design them later (don't want just to copy from stable/lazer).
- Auto is an option of play mode.
=> Implement play & DA mods

src/nmania/Player.java, src/nmania/RichSkin.java, src/nmania/Skin.java, src/nmania/ui/BeatmapSetsList.java, src/nmania/ui/MainScreen.java, src/nmania/ui/SkinSelect.java
=> Rich skin implementation

src/nmania/ui/ng/Alert.java, src/nmania/ui/ng/BrowserDownloader.java, src/nmania/ui/ng/BrowserList.java, src/nmania/ui/ng/BrowserSearch.java, src/nmania/ui/ng/BrowserView.java, src/nmania/ui/ng/MainScreen.java
=> Beatmpas browser

.github/workflows/build.yml, build.sh, build_sub.sh, src/nmania/Player.java
=> Add 3 build ways

src/nmania/Settings.java, src/nmania/ui/ng/SettingsScreen.java
=> External settings

build.sh, build_sub.sh, proguard.basecfg
=> Add proguard support

src/nmania/Player.java, src/nmania/Settings.java, src/nmania/ui/ng/NmaniaDisplay.java, src/nmania/ui/ng/VisualSettings.java
Should help with floating-point issues. And generally looks better.
Fix #70
=> Make dim level integer

src/nmania/ui/ng/ListScreen.java
=> Scroll selected items

src/nmania/Nmania.java, src/nmania/ui/KeyboardSetup.java, src/symnovel/SNUtils.java
Side effect: fixed UI freeze when exiting KB setup
=> Do not use midlet object

src/nmania/ui/ng/Alert.java, src/nmania/ui/ng/IDisplay.java, src/nmania/ui/ng/ListScreen.java, src/nmania/ui/ng/ModsSelectScreen.java, src/nmania/ui/ng/Screen.java, src/nmania/ui/ng/SkinSelectScreen.java
Brings standardized key codes as well as falling back to game actions.
=> Game actions checks

build_sub.sh, src/nmania/ui/ng/Alert.java, src/nmania/ui/ng/ListScreen.java, src/nmania/ui/ng/ModsSelectScreen.java, src/nmania/ui/ng/NmaniaDisplay.java, src/nmania/ui/ng/NumberBox.java, src/nmania/ui/ng/PlayerLoaderScreen.java, src/nmania/ui/ng/Screen.java, src/nmania/ui/ng/SkinSelectScreen.java
Added delta to callback's params.
=> Better touch event

src/nmania/ui/ng/NmaniaDisplay.java
=> Add tap effect

src/nmania/ui/ng/VisualSettings.java
=> Add ability to edit dim and scroll speed with numbox

src/nmania/ui/ng/ModsSelectScreen.java
=> Add touch support for mods select

.github/workflows/build.yml, .gitignore, src/nmania/AudioController.java, src/nmania/Nmania.java, src/nmania/Player.java, src/nmania/PlayerLoader.java, src/nmania/PlayerThread.java, src/nmania/Settings.java, src/nmania/ui/ResultsScreen.java, src/nmania/ui/ng/DifficultySelect.java, src/nmania/ui/ng/MainScreen.java, src/nmania/ui/ng/ModsSelectScreen.java, src/nmania/ui/ng/NmaniaDisplay.java, src/nmania/ui/ng/SettingsScreen.java, tests/RecGenerator/Program.cs, tests/RecGenerator/RecGenerator.csproj, tests/RecGenerator/RecGenerator.sln, tests/TestResultsProcessor/Analyzer.cs, tests/TestResultsProcessor/Program.cs, tests/TestResultsProcessor/TestResultsProcessor.csproj, tests/TestResultsProcessor/TestResultsProcessor.sln, tests/basic.txt, tests/basic_sets.json, tests/rec_check.py
=> Add full UI test workflow

src/nmania/Player.java
Pointer pressed on column enables it. Releasing this pointer disables it. There is no limit of simultaneously holded pointers.
Closes #61
Preregs:
=> Support multitouch in gameplay

src/nmania/ui/ng/NmaniaDisplay.java
=> Always draw disc under logo

src/nmania/ui/ng/NmaniaDisplay.java
=> Do not draw left button when hidden

src/nmania/ui/ng/AudioSettings.java
=> Add help submenu for audio settings

Application Descriptor, src/nmania/Nmania.java, src/nmania/Player.java
=> Freeze UI on app minimize

src/nmania/Player.java, src/nmania/ScoreController.java
=> Fix restart issues

src/nmania/Player.java, src/nmania/PlayerThread.java
=> Remove useless flushes to fix flickering

src/nmania/Player.java
Попытка починить мультитач на ж2мел.
=> Multitouch logging

src/nmania/ScoreController.java
=> Track max ticks for max combo

src/nmania/ui/KeyboardSetup.java
=> Force settings save on keyboard layout change

src/nmania/AudioController.java, src/nmania/Player.java, src/nmania/PlayerLoader.java, src/nmania/ui/ResultsScreen.java, src/nmania/ui/ng/BMSSelect.java, src/nmania/ui/ng/ListScreen.java, src/nmania/ui/ng/NmaniaDisplay.java, src/nmania/ui/ng/PlayerLoaderScreen.java, src/nmania/ui/ng/Screen.java
=> Visuals cleanup

src/nmania/ui/ng/ColorBox.java, src/nmania/ui/ng/ListScreen.java, src/nmania/ui/ng/NumberBox.java, src/nmania/ui/ng/PalleteBox.java
Closes #64 
Closes #65 
Closes #104
=> Color boxes

src/nmania/Player.java, src/nmania/Settings.java, src/nmania/ui/ng/NumberBox.java, src/nmania/ui/ng/ScrollSpeedBox.java, src/nmania/ui/ng/VisualSettings.java
=> Scroll speed

src/nmania/ui/ng/NmaniaDisplay.java, src/nmania/ui/ng/SkinSelectScreen.java
=> Ignore multitouch in menu and display ignored touches

src/nmania/Player.java, src/nmania/Settings.java, src/nmania/skin/RasterSkin.java, src/nmania/skin/Skin.java, src/nmania/skin/VectorSkin.java, src/nmania/ui/ng/RasterSkinSettings.java, src/nmania/ui/ng/SystemSettings.java, src/nmania/ui/ng/VectorSkinSettings.java
=> Raster judgments & borders skinning
